### ISSUE TITLE
終盤の難しさを軽減したい

### ISSUE THREAD

**Issue by noir-neo** [one-night-game-jam/joya-no-kane#31]
現状クリア困難すぎる。

アイデアとしては、
鐘撞く度にスピードアップして、
デフォルトはもう少し遅くする。
序盤になるべく一気に倒すのがタイムに結びつくかなと

**Comment by maku693** [comment]
結構よさそう。やってみてどうかみてみたい。

あと思いつくのは、直進し続けると加速するとかかな〜.

**Comment by maku693** [comment]
あとバトロワ系みたいに、ゲームの進行に応じてステージが狭くなるとか？ ゲームのゴールとコンフリクトするかな

**Comment by maku693** [comment]
あと、別にデフォルト速くない気がしてて、むしろもう少し全体的に速い方がたのしいかな〜とは思う。

**Comment by noir-neo** [comment]
あー直進加速は普通にやってもいいと思ってた。楽しそう

**Comment by noir-neo** [comment]
タスクは作ったので close
